### PR TITLE
Support StartTLS and Bind, and update LDAP params to config file

### PR DESCRIPTION
**Pull request by kyle-williams-1**
Support StartTLS and Bind, and update LDAP params to config file

### CODE REVIEW

**Comment by ThoreKr** [comment]
Looks cool.

Still haven't found the time to replace this ldapWorker function with a function which gets triggered on every scrape. Hope to get this done someday at the end of this month.

**Comment by kyle-williams-1** [comment]
Off topic here a little bit, but how do you effectively compare contextCSN's across multiple LDAP servers, while ensuring they don't change between scrapes?

**Comment by ThoreKr** [comment]
We don't have the exporter running yet but I planned to use it with a small threshold to give it some time to replicate. We don't have constant changes though. It's more intended to be a continuous health indicator.

**Comment by kyle-williams-1** [comment]
Is the conversion of the contextCSN (with date embedded) to a float 64 so that you can easily do that numeric small threshold comparison?

**Comment by ThoreKr** [comment]
The reason why it is a float64 is the datatype the [prometheus library](https://godoc.org/github.com/prometheus/client_golang/prometheus#Gauge) chose to use.

I don't know of a way to expose the contextCSN as a metric. You could do weird things with labels though, but that's really ugly. Since YMD timestamps also are quite useless to store there is this conversion into a unix timestamp which is way more general and can be exposed as a metric.

**Pull request merged**
